[package]
name = "oink"
version = "0.1.0"
edition = "2021"

[dependencies]
comrak = "0.12.1"
handlebars = "4.1.6"
serde = { version = "1.0.132", features = ["derive"] }
serde_yaml = "0.8.23"
serde_json = "1.0.73"
regex = "1.5.4"